#ifndef __GLOBALS_H__
#define __GLOBALS_H__

//  ACTIVE GAME FLAGS
#define GAME_FLAG(game)					(1 << (int(game) + 1))

#define PROGRESSIVE_BUILD				0
#if PROGRESSIVE_BUILD
#define ACTIVE_GAME_FLAG				GAME_FLAG(GameName::Progressive)
#define DEFAULT_STARTING_CREDITS		400000
#define DEFAULT_STARTING_DENOM			25
#else
#define ACTIVE_GAME_FLAG				GAME_FLAG(GameName::SuperGoldMine) + GAME_FLAG(GameName::SuperCash) + GAME_FLAG(GameName::SuperWild) + GAME_FLAG(GameName::SuperBonus) + GAME_FLAG(GameName::SuperPattern) + GAME_FLAG(GameName::SuperMatch) + GAME_FLAG(GameName::SuperMystery)
#define DEFAULT_STARTING_CREDITS		400000
#define DEFAULT_STARTING_DENOM			25
#endif
//#define ACTIVE_GAME_FLAG				GAME_FLAG(GameName::SuperGoldMine) + GAME_FLAG(GameName::SuperCash) + GAME_FLAG(GameName::SuperWild) + GAME_FLAG(GameName::SuperBonus) + GAME_FLAG(GameName::SuperPattern) + GAME_FLAG(GameName::Progressive)

#define IS_GAME_ACTIVE(flag)			((flag == -1) || ((ACTIVE_GAME_FLAG & GAME_FLAG(flag)) != 0))

// BASE GAME DEFINES
#define NUM_START_CARDS						1
#define NUM_MAX_CARDS						9
#define MAX_BET								5
#define MAX_PATTERN_BET						9
#define NUM_LOCAL_PROGRESSIVES				3
#define NUM_GLOBAL_PROGRESSIVES				4
#define MAX_NUM_CARDS						9
#define MAX_NUM_WILD_BALLS					75
#define MAX_PATTERN_BET						9
#define NETWORK_PLAY						0
#define NUM_CARDS_IN_PERM_DECK				15000
#define WIN_CELEBRATION_MINIMUM				201
#define LARGE_WIN_CELEBRATION_MINIMUM		251
#define MILLISECONDS_BETWEEN_HELP_PATTERNS	1000

// TESTING DEFINES
#define TEST_LOW_CREDITS					0
#define TEST_SHORT_CIRCUIT_STATE_MACHINE	0

// DISPLAY DEFINES
#define DISPLAY_DEFAULT_WINDOW_WIDTH		1280
#define DISPLAY_DEFAULT_WINDOW_HEIGHT		720
#define DISPLAY_HALF_WINDOW_WIDTH			640
#define DISPLAY_HALF_WINDOW_HEIGHT			360
#define DISPLAY_BALL_FADE_TIME				3
#define DISPLAY_ATTRACT_START_TIME			300			// 300 Seconds = 5 Minutes
#define DISPLAY_TIME_BEFORE_RED_CLOUD		0
#define DISPLAY_RESOLUTION_4x3_CUT_OFF		1.45		// 1.55
#define DISPLAY_RESOLUTION_3x2_CUT_OFF		1.55
#define DISPLAY_RESOLUTION_WXGA_CUT_OFF		1.68

#define DISPLAY_TIME_BEFORE_TOP_UPDATE		10
#define DISPLAY_4x3_SHIFT					-165
#define DISPLAY_3x2_SHIFT					-85			// -45
#define DISPLAY_3x2_SHIFT_LARGE				-100
#define DISPLAY_WXGA_SHIFT					-70

#define DISPLAY_BALL_CALL_RUN_TIME_1		1700
#define DISPLAY_BALL_CALL_RUN_TIME_2		2200
#define DISPLAY_BALL_CALL_RUN_TIME_3		1900
#define DISPLAY_BALL_CALL_RUN_TIME_4		2600
#define DISPLAY_BALL_CALL_RUN_TIME_5		2300
#define DISPLAY_BALL_CALL_RUN_TIME_6		3200
#define DISPLAY_BALL_CALL_RUN_TIME_7		2600
#define DISPLAY_BALL_CALL_RUN_TIME_8		2800
#define DISPLAY_BALL_CALL_RUN_TIME_9		2800
#define DISPLAY_BALL_CALL_RUN_TIME_10		2800

#define DISPLAY_BALL_CALL_LIST_SIZE_1		8
#define DISPLAY_BALL_CALL_LIST_SIZE_2		11
#define DISPLAY_BALL_CALL_LIST_SIZE_3		16
#define DISPLAY_BALL_CALL_LIST_SIZE_4		20
#define DISPLAY_BALL_CALL_LIST_SIZE_5		27
#define DISPLAY_BALL_CALL_LIST_SIZE_6		34
#define DISPLAY_BALL_CALL_LIST_SIZE_7		43
#define DISPLAY_BALL_CALL_LIST_SIZE_8		56
#define DISPLAY_BALL_CALL_LIST_SIZE_9		66
#define DISPLAY_BALL_CALL_LIST_SIZE_10		75

// Hard coded defaults for values on canvases/objects that change for special game modes.
#define DEFAULT_DENOM_X_POS					0
#define PROGRES_DENOM_X_POS					-55
#define DEFAULT_CARDS_X_POS					0
#define PROGRES_CARDS_X_POS					10
#define PAYTABLE_Y_ROW_UPDATE				13
#define DEFAULT_BINGOCARD_X_POS				968
#define PROGRES_BINGOCARD_X_POS				968
#define PATTERN_TYPENAME_BASE_POS			542
#define PATTERN_TYPENAME_WILD_POS			200

#endif // __GLOBALS_H__