#ifndef PROGRESSIVESYSTEM_H
#define PROGRESSIVESYSTEM_H

// Progressive system constants
#define SPOOF_MULTIPLIER		4
#define SPOOF_TIMER_RESET		9
#define LOCAL_JACKPOT_LOW		15
#define LOCAL_JACKPOT_HIGH		29
#define GLOBAL_JACKPOT_LOW		149
#define GLOBAL_JACKPOT_HIGH		199
#define TIME_FOR_MINI_UPDATE	1500
#define TIME_FOR_MIDI_UPDATE	1000
#define TIME_FOR_GRAND_UPDATE	800
#define TIME_FOR_JACKPOT_UPDATE	400
#define TIME_INCREMENT_LOCAL	1000

#define PROG_JACKPOT_WIN		5852925
#define PROG_GRAND_WIN			731616
#define PROG_MIDI_WIN			162581
#define PROG_MINI_WIN			48774

#endif // PROGRESSIVESYSTEM_H