#ifndef _SOUND_PLAY_H_
#define _SOUND_PLAY_H_

enum SOUND_BANK
{
	SOUND_COIN_FALL,
	SOUND_PLAY_BUTTON,
	SOUND_ADD_CARD_1,
	SOUND_ADD_CARD_4,
	SOUND_ADD_CARD_9,
	SOUND_UI_BUTTON,
	SOUND_BET_MAX_BUTTON,
	SOUND_BET_ONE_1,
	SOUND_BET_ONE_2,
	SOUND_BET_ONE_3,
	SOUND_BET_ONE_4,
	SOUND_BET_ONE_5,
	SOUND_BET_ONE_6,
	SOUND_BET_ONE_7,
	SOUND_BET_ONE_8,
	SOUND_BET_ONE_9,
	SOUND_BETVALUE_1,
	SOUND_BETVALUE_2,
	SOUND_BETVALUE_3,
	SOUND_BETVALUE_4,
	SOUND_BETVALUE_5,
	SOUND_BETVALUE_6,
	SOUND_BETVALUE_7,
	SOUND_CHANGE_CARDS,
	SOUND_CREDIT_ROLL,
	SOUND_CREDIT_ROLL_END,
	SOUND_FREE_PLAY_WIN,
	SOUND_CASH_BALL_WIN,
	SOUND_PROGRESSIVE_WIN,
	SOUND_CASH_BALL,
	SOUND_WILD_BALL,
	SOUND_BONUS_BALL,
	SOUND_BINGO_WIN_1,
	SOUND_BINGO_WIN_2,
	SOUND_BINGO_WIN_3,
	SOUND_BALLOON,
	SOUND_BALLHIT,
	SOUND_CELEBRATION_BANKER,
	SOUND_CELEBRATION_ERNIE,
	SOUND_CELEBRATION_MINER,
	SOUND_CELEBRATION_MONKEY,
	SOUND_CELEBRATION_SQUIGGY,
	SOUND_CELEBRATION_THROW1,
	SOUND_CELEBRATION_THROW2,
	SOUND_CELEBRATION_TRUMPET,
	SOUND_LAUGH_BANKER,
	SOUND_LAUGH_ERNIE,
	SOUND_LAUGH_MINER,
	SOUND_LAUGH_MONKEY,
	SOUND_LAUGH_SQUIGGY,
	SOUND_LOGO_CLICK_EASTER_EGG_1,
	SOUND_LOGO_CLICK_EASTER_EGG_2,
	SOUND_LOGO_CLICK_EASTER_EGG_3,
	SOUND_LOGO_CLICK_EASTER_EGG_4,
	SOUND_LOGO_CLICK_EASTER_EGG_5,
	SOUND_LOGO_CLICK_EASTER_EGG_6,
	SOUND_LOGO_CLICK_EASTER_EGG_7,
	SOUND_LOGO_CLICK_EASTER_EGG_8,
	SOUND_LOGO_CLICK_EASTER_EGG_9,
	SOUND_LOGO_CLICK_EASTER_EGG_10,
	SOUND_LOGO_CLICK_EASTER_EGG_11,
	SOUND_LOGO_CLICK_EASTER_EGG_12,
	SOUND_BIGWIN_ROLLUP_START,
	SOUND_BIGWIN_ROLLUP_LOOP1,
	SOUND_BIGWIN_ROLLUP_LOOP2,
	SOUND_BIGWIN_ROLLUP_LOOP3,
	SOUND_BIGWIN_ROLLUP_LOOP4,
	SOUND_BIGWIN_ROLLUP_FINISH,
	SOUND_BANK_MAX
};

enum SOUND_CHANNELS
{
	SOUND_CH_MENU_MUSIC,
	SOUND_CH_MENU_OPTION,
	SOUND_CH_TALLY_UP,
	SOUND_CH_CHAR_CHEER,
	SOUND_CH_EASTER_EGG,
	SOUND_CH_CHAR_BIGCHEER,
	SOUND_CH_FIRST_BALL,
	SOUND_CH_LAST_BALL,
	SOUND_CH_BASIC_WIN,
	SOUND_CH_BALL_FALL,
	SOUND_CH_CLOUDWIN1,
	SOUND_CH_CLOUDWIN2,
	SOUND_CHANNEL_COUNT
};

void IterateSoundVolume();
int GetSoundSetting();

void SoundInit();
void LoadSoundFile(const char* soundname, SOUND_BANK bank_pos);
void PlaySoundFile(SOUND_BANK bank_pos, bool repeat);
bool IsSoundPlaying();
void StopSoundFiles();
void StopSoundAllChannels();
void ChangeSoundChannel(int newChannel);


#endif // _SOUND_PLAY_H_